const EMOTICON_MAP: [RegExp, string][] = [
  [/:-?\)/g,  "😊"], [/:-?D/g,   "😄"], [/:-?\(/g,  "😔"],
  [/;-?\)/g,  "😉"], [/:-?P/gi,  "😛"], [/:-?\*/g,  "😘"],
  [/:-?O/gi,  "😮"], [/:-?\|/g,  "😐"], [/>:-?\(/g, "😠"],
  [/:-?\//g,  "😕"], [/:'?\(/g,  "😢"], [/\^_?\^/g, "😊"],
  [/<3/g,     "❤️"], [/<\/3/g,   "💔"], [/B-?\)/g,  "😎"],
  [/:-?X/gi,  "🤐"], [/O:-?\)/g, "😇"], [/:-?S/gi,  "😖"],
];

const EMOJI_SHORTCODES: { name: string; emoji: string }[] = [
  { name: "thumbsup", emoji: "👍" }, { name: "+1", emoji: "👍" },
  { name: "thumbsdown", emoji: "👎" }, { name: "-1", emoji: "👎" },
  { name: "heart", emoji: "❤️" }, { name: "red_heart", emoji: "❤️" },
  { name: "laughing", emoji: "😂" }, { name: "joy", emoji: "😂" }, { name: "lol", emoji: "😂" },
  { name: "rofl", emoji: "🤣" },
  { name: "smile", emoji: "😊" }, { name: "blush", emoji: "😊" },
  { name: "grin", emoji: "😁" }, { name: "wink", emoji: "😉" },
  { name: "stuck_out_tongue", emoji: "😛" }, { name: "tongue", emoji: "😛" },
  { name: "sunglasses", emoji: "😎" }, { name: "cool", emoji: "😎" },
  { name: "thinking", emoji: "🤔" },
  { name: "hushed", emoji: "😮" }, { name: "open_mouth", emoji: "😮" },
  { name: "cry", emoji: "😢" }, { name: "crying", emoji: "😢" },
  { name: "sob", emoji: "😭" }, { name: "scream", emoji: "😱" },
  { name: "angry", emoji: "😠" }, { name: "rage", emoji: "😡" },
  { name: "fire", emoji: "🔥" }, { name: "flame", emoji: "🔥" },
  { name: "tada", emoji: "🎉" }, { name: "party", emoji: "🎉" },
  { name: "eyes", emoji: "👀" }, { name: "wave", emoji: "👋" },
  { name: "pray", emoji: "🙏" }, { name: "100", emoji: "💯" },
  { name: "ok", emoji: "👌" }, { name: "ok_hand", emoji: "👌" },
  { name: "clap", emoji: "👏" }, { name: "muscle", emoji: "💪" },
  { name: "rocket", emoji: "🚀" }, { name: "star", emoji: "⭐" },
  { name: "sparkles", emoji: "✨" },
  { name: "check", emoji: "✅" }, { name: "white_check_mark", emoji: "✅" },
  { name: "x", emoji: "❌" }, { name: "no", emoji: "❌" },
  { name: "broken_heart", emoji: "💔" }, { name: "poop", emoji: "💩" },
  { name: "skull", emoji: "💀" }, { name: "dead", emoji: "💀" },
  { name: "exploding_head", emoji: "🤯" }, { name: "mind_blown", emoji: "🤯" },
  { name: "salute", emoji: "🫡" }, { name: "hug", emoji: "🤗" },
  { name: "shrug", emoji: "🤷" }, { name: "facepalm", emoji: "🤦" },
  { name: "chef_kiss", emoji: "🤌" }, { name: "raised_hands", emoji: "🙌" },
  { name: "heart_eyes", emoji: "😍" }, { name: "kiss", emoji: "😘" },
  { name: "yum", emoji: "😋" }, { name: "monocle", emoji: "🧐" },
  { name: "zipper_mouth", emoji: "🤐" }, { name: "sweat_smile", emoji: "😅" },
  { name: "flushed", emoji: "😳" }, { name: "pleading", emoji: "🥺" },
  { name: "pensive", emoji: "😔" }, { name: "sleeping", emoji: "😴" },
  { name: "nerd", emoji: "🤓" }, { name: "ghost", emoji: "👻" },
  { name: "alien", emoji: "👽" }, { name: "robot", emoji: "🤖" },
  { name: "cat", emoji: "🐱" }, { name: "dog", emoji: "🐶" },
  { name: "pizza", emoji: "🍕" }, { name: "beer", emoji: "🍺" },
  { name: "coffee", emoji: "☕" }, { name: "cake", emoji: "🎂" },
  { name: "trophy", emoji: "🏆" }, { name: "medal", emoji: "🥇" },
  { name: "music", emoji: "🎵" }, { name: "microphone", emoji: "🎤" },
  { name: "phone", emoji: "📱" }, { name: "computer", emoji: "💻" },
  { name: "email", emoji: "📧" }, { name: "bulb", emoji: "💡" },
  { name: "warning", emoji: "⚠️" }, { name: "lock", emoji: "🔒" },
  { name: "key", emoji: "🔑" }, { name: "moneybag", emoji: "💰" },
  // ── uitgebreid (gezichten, handen, harten, dieren, eten, natuur, doen,
  //    reizen, dingen, tekens). Engelse namen zoals Slack en Discord ze
  //    kennen; `:monk` vond hier eerst niets.
  { name: "slightly_smiling", emoji: "🙂" }, { name: "upside_down", emoji: "🙃" },
  { name: "smiley", emoji: "😃" }, { name: "grinning", emoji: "😀" },
  { name: "sweat", emoji: "😓" }, { name: "relieved", emoji: "😌" },
  { name: "innocent", emoji: "😇" }, { name: "halo", emoji: "😇" },
  { name: "smirk", emoji: "😏" }, { name: "unamused", emoji: "😒" },
  { name: "roll_eyes", emoji: "🙄" }, { name: "eye_roll", emoji: "🙄" },
  { name: "grimacing", emoji: "😬" }, { name: "neutral", emoji: "😐" },
  { name: "expressionless", emoji: "😑" }, { name: "no_mouth", emoji: "😶" },
  { name: "star_struck", emoji: "🤩" }, { name: "partying", emoji: "🥳" },
  { name: "smiling_hearts", emoji: "🥰" }, { name: "in_love", emoji: "🥰" },
  { name: "kissing", emoji: "😗" }, { name: "zany", emoji: "🤪" },
  { name: "crazy", emoji: "🤪" }, { name: "money_mouth", emoji: "🤑" },
  { name: "shush", emoji: "🤫" }, { name: "shushing", emoji: "🤫" },
  { name: "hand_over_mouth", emoji: "🤭" }, { name: "lying", emoji: "🤥" },
  { name: "drooling", emoji: "🤤" }, { name: "sleepy", emoji: "😪" },
  { name: "mask", emoji: "😷" }, { name: "sick", emoji: "🤒" },
  { name: "nauseated", emoji: "🤢" }, { name: "vomit", emoji: "🤮" },
  { name: "sneeze", emoji: "🤧" }, { name: "hot", emoji: "🥵" },
  { name: "cold", emoji: "🥶" }, { name: "woozy", emoji: "🥴" },
  { name: "dizzy_face", emoji: "😵" }, { name: "cowboy", emoji: "🤠" },
  { name: "disguise", emoji: "🥸" }, { name: "confused", emoji: "😕" },
  { name: "worried", emoji: "😟" }, { name: "frowning", emoji: "☹️" },
  { name: "astonished", emoji: "😲" }, { name: "fearful", emoji: "😨" },
  { name: "anxious", emoji: "😰" }, { name: "disappointed", emoji: "😞" },
  { name: "persevere", emoji: "😣" }, { name: "weary", emoji: "😩" },
  { name: "tired", emoji: "😫" }, { name: "yawn", emoji: "🥱" },
  { name: "triumph", emoji: "😤" }, { name: "cursing", emoji: "🤬" },
  { name: "devil", emoji: "😈" }, { name: "imp", emoji: "👿" },
  { name: "clown", emoji: "🤡" }, { name: "melting", emoji: "🫠" },
  { name: "holding_back_tears", emoji: "🥹" }, { name: "saluting", emoji: "🫡" },
  { name: "peeking", emoji: "🫣" }, { name: "dotted_face", emoji: "🫥" },
  { name: "see_no_evil", emoji: "🙈" }, { name: "hear_no_evil", emoji: "🙉" },
  { name: "speak_no_evil", emoji: "🙊" }, { name: "monkey", emoji: "🐒" },
  { name: "monkey_face", emoji: "🐵" },
  // De drie wijze apen ook onder "monkey": `:monk` moet ze allemaal geven,
  // niet alleen wie toevallig al "monkey" in zijn naam had.
  { name: "monkey_eyes", emoji: "🙈" }, { name: "monkey_covering_eyes", emoji: "🙈" },
  { name: "monkey_ears", emoji: "🙉" }, { name: "monkey_covering_ears", emoji: "🙉" },
  { name: "monkey_mouth", emoji: "🙊" }, { name: "monkey_covering_mouth", emoji: "🙊" },
  { name: "gorilla", emoji: "🦍" }, { name: "orangutan", emoji: "🦧" }, { name: "ape", emoji: "🦍" },
  // handen en lijf
  { name: "raised_hand", emoji: "✋" }, { name: "high_five", emoji: "🙌" },
  { name: "v", emoji: "✌️" }, { name: "peace", emoji: "✌️" },
  { name: "crossed_fingers", emoji: "🤞" }, { name: "fingers_crossed", emoji: "🤞" },
  { name: "love_you", emoji: "🤟" }, { name: "metal", emoji: "🤘" },
  { name: "rock_on", emoji: "🤘" }, { name: "call_me", emoji: "🤙" },
  { name: "point_left", emoji: "👈" }, { name: "point_right", emoji: "👉" },
  { name: "point_up", emoji: "👆" }, { name: "point_down", emoji: "👇" },
  { name: "middle_finger", emoji: "🖕" }, { name: "fist", emoji: "✊" },
  { name: "punch", emoji: "👊" }, { name: "fist_bump", emoji: "👊" },
  { name: "handshake", emoji: "🤝" }, { name: "open_hands", emoji: "👐" },
  { name: "palms_up", emoji: "🤲" }, { name: "writing", emoji: "✍️" },
  { name: "nail_care", emoji: "💅" }, { name: "selfie", emoji: "🤳" },
  { name: "flex", emoji: "💪" }, { name: "brain", emoji: "🧠" },
  { name: "eye", emoji: "👁️" }, { name: "lips", emoji: "👄" },
  { name: "baby", emoji: "👶" }, { name: "person_bowing", emoji: "🙇" },
  { name: "dancer", emoji: "💃" }, { name: "dancing", emoji: "🕺" },
  { name: "runner", emoji: "🏃" }, { name: "running", emoji: "🏃" },
  { name: "walking", emoji: "🚶" }, { name: "surfer", emoji: "🏄" },
  { name: "surfing", emoji: "🏄" }, { name: "swimmer", emoji: "🏊" },
  { name: "biking", emoji: "🚴" }, { name: "cyclist", emoji: "🚴" },
  { name: "lotus", emoji: "🧘" }, { name: "yoga", emoji: "🧘" },
  // harten
  { name: "orange_heart", emoji: "🧡" }, { name: "yellow_heart", emoji: "💛" },
  { name: "green_heart", emoji: "💚" }, { name: "blue_heart", emoji: "💙" },
  { name: "purple_heart", emoji: "💜" }, { name: "black_heart", emoji: "🖤" },
  { name: "white_heart", emoji: "🤍" }, { name: "brown_heart", emoji: "🤎" },
  { name: "pink_heart", emoji: "🩷" }, { name: "two_hearts", emoji: "💕" },
  { name: "sparkling_heart", emoji: "💖" }, { name: "heartbeat", emoji: "💓" },
  { name: "growing_heart", emoji: "💗" }, { name: "revolving_hearts", emoji: "💞" },
  { name: "heart_exclamation", emoji: "❣️" }, { name: "cupid", emoji: "💘" },
  { name: "gift_heart", emoji: "💝" }, { name: "love_letter", emoji: "💌" },
  { name: "heart_on_fire", emoji: "❤️‍🔥" }, { name: "mending_heart", emoji: "❤️‍🩹" },
  // dieren
  { name: "cat_face", emoji: "😺" }, { name: "kitten", emoji: "🐈" },
  { name: "puppy", emoji: "🐕" }, { name: "poodle", emoji: "🐩" },
  { name: "wolf", emoji: "🐺" }, { name: "fox", emoji: "🦊" },
  { name: "raccoon", emoji: "🦝" }, { name: "lion", emoji: "🦁" },
  { name: "tiger", emoji: "🐯" }, { name: "leopard", emoji: "🐆" },
  { name: "horse", emoji: "🐴" }, { name: "unicorn", emoji: "🦄" },
  { name: "zebra", emoji: "🦓" }, { name: "cow", emoji: "🐮" },
  { name: "pig", emoji: "🐷" }, { name: "boar", emoji: "🐗" },
  { name: "sheep", emoji: "🐑" }, { name: "goat", emoji: "🐐" },
  { name: "camel", emoji: "🐫" }, { name: "llama", emoji: "🦙" },
  { name: "giraffe", emoji: "🦒" }, { name: "elephant", emoji: "🐘" },
  { name: "rhino", emoji: "🦏" }, { name: "hippo", emoji: "🦛" },
  { name: "mouse", emoji: "🐭" }, { name: "rat", emoji: "🐀" },
  { name: "hamster", emoji: "🐹" }, { name: "rabbit", emoji: "🐰" },
  { name: "bunny", emoji: "🐇" }, { name: "hedgehog", emoji: "🦔" },
  { name: "bat", emoji: "🦇" }, { name: "bear", emoji: "🐻" },
  { name: "polar_bear", emoji: "🐻‍❄️" }, { name: "koala", emoji: "🐨" },
  { name: "panda", emoji: "🐼" }, { name: "sloth", emoji: "🦥" },
  { name: "otter", emoji: "🦦" }, { name: "skunk", emoji: "🦨" },
  { name: "kangaroo", emoji: "🦘" }, { name: "badger", emoji: "🦡" },
  { name: "chicken", emoji: "🐔" }, { name: "rooster", emoji: "🐓" },
  { name: "chick", emoji: "🐤" }, { name: "bird", emoji: "🐦" },
  { name: "penguin", emoji: "🐧" }, { name: "dove", emoji: "🕊️" },
  { name: "eagle", emoji: "🦅" }, { name: "duck", emoji: "🦆" },
  { name: "swan", emoji: "🦢" }, { name: "owl", emoji: "🦉" },
  { name: "flamingo", emoji: "🦩" }, { name: "peacock", emoji: "🦚" },
  { name: "parrot", emoji: "🦜" }, { name: "frog", emoji: "🐸" },
  { name: "crocodile", emoji: "🐊" }, { name: "turtle", emoji: "🐢" },
  { name: "lizard", emoji: "🦎" }, { name: "snake", emoji: "🐍" },
  { name: "dragon", emoji: "🐉" }, { name: "dinosaur", emoji: "🦖" },
  { name: "t_rex", emoji: "🦖" }, { name: "whale", emoji: "🐳" },
  { name: "dolphin", emoji: "🐬" }, { name: "seal", emoji: "🦭" },
  { name: "fish", emoji: "🐟" }, { name: "tropical_fish", emoji: "🐠" },
  { name: "blowfish", emoji: "🐡" }, { name: "shark", emoji: "🦈" },
  { name: "octopus", emoji: "🐙" }, { name: "shell", emoji: "🐚" },
  { name: "crab", emoji: "🦀" }, { name: "lobster", emoji: "🦞" },
  { name: "shrimp", emoji: "🦐" }, { name: "squid", emoji: "🦑" },
  { name: "snail", emoji: "🐌" }, { name: "butterfly", emoji: "🦋" },
  { name: "bug", emoji: "🐛" }, { name: "ant", emoji: "🐜" },
  { name: "bee", emoji: "🐝" }, { name: "honeybee", emoji: "🐝" },
  { name: "ladybug", emoji: "🐞" }, { name: "spider", emoji: "🕷️" },
  { name: "mosquito", emoji: "🦟" }, { name: "paw_prints", emoji: "🐾" },
  // natuur en weer
  { name: "sun", emoji: "☀️" }, { name: "sunny", emoji: "☀️" },
  { name: "partly_sunny", emoji: "⛅" }, { name: "cloud", emoji: "☁️" },
  { name: "rain", emoji: "🌧️" }, { name: "umbrella", emoji: "☔" },
  { name: "thunder", emoji: "⛈️" }, { name: "zap", emoji: "⚡" },
  { name: "lightning", emoji: "⚡" }, { name: "snow", emoji: "❄️" },
  { name: "snowflake", emoji: "❄️" }, { name: "snowman", emoji: "⛄" },
  { name: "rainbow", emoji: "🌈" }, { name: "tornado", emoji: "🌪️" },
  { name: "fog", emoji: "🌫️" }, { name: "wind", emoji: "🌬️" },
  { name: "ocean", emoji: "🌊" }, { name: "wave_water", emoji: "🌊" },
  { name: "droplet", emoji: "💧" }, { name: "moon", emoji: "🌙" },
  { name: "full_moon", emoji: "🌕" }, { name: "new_moon", emoji: "🌑" },
  { name: "earth", emoji: "🌍" }, { name: "globe", emoji: "🌍" },
  { name: "comet", emoji: "☄️" }, { name: "star2", emoji: "🌟" },
  { name: "glowing_star", emoji: "🌟" }, { name: "dizzy", emoji: "💫" },
  { name: "sunrise", emoji: "🌅" }, { name: "sunset", emoji: "🌇" },
  { name: "mountain", emoji: "⛰️" }, { name: "volcano", emoji: "🌋" },
  { name: "beach", emoji: "🏖️" }, { name: "desert", emoji: "🏜️" },
  { name: "island", emoji: "🏝️" }, { name: "camping", emoji: "🏕️" },
  { name: "tree", emoji: "🌳" }, { name: "evergreen", emoji: "🌲" },
  { name: "palm_tree", emoji: "🌴" }, { name: "cactus", emoji: "🌵" },
  { name: "seedling", emoji: "🌱" }, { name: "herb", emoji: "🌿" },
  { name: "shamrock", emoji: "☘️" }, { name: "four_leaf_clover", emoji: "🍀" },
  { name: "leaves", emoji: "🍃" }, { name: "fallen_leaf", emoji: "🍂" },
  { name: "maple_leaf", emoji: "🍁" }, { name: "mushroom", emoji: "🍄" },
  { name: "flower", emoji: "🌸" }, { name: "cherry_blossom", emoji: "🌸" },
  { name: "rose", emoji: "🌹" }, { name: "wilted_rose", emoji: "🥀" },
  { name: "tulip", emoji: "🌷" }, { name: "sunflower", emoji: "🌻" },
  { name: "hibiscus", emoji: "🌺" }, { name: "bouquet", emoji: "💐" },
  // eten en drinken
  { name: "apple", emoji: "🍎" }, { name: "green_apple", emoji: "🍏" },
  { name: "pear", emoji: "🍐" }, { name: "orange", emoji: "🍊" },
  { name: "tangerine", emoji: "🍊" }, { name: "lemon", emoji: "🍋" },
  { name: "banana", emoji: "🍌" }, { name: "watermelon", emoji: "🍉" },
  { name: "grapes", emoji: "🍇" }, { name: "strawberry", emoji: "🍓" },
  { name: "blueberries", emoji: "🫐" }, { name: "melon", emoji: "🍈" },
  { name: "cherries", emoji: "🍒" }, { name: "peach", emoji: "🍑" },
  { name: "mango", emoji: "🥭" }, { name: "pineapple", emoji: "🍍" },
  { name: "coconut", emoji: "🥥" }, { name: "kiwi", emoji: "🥝" },
  { name: "tomato", emoji: "🍅" }, { name: "avocado", emoji: "🥑" },
  { name: "eggplant", emoji: "🍆" }, { name: "potato", emoji: "🥔" },
  { name: "carrot", emoji: "🥕" }, { name: "corn", emoji: "🌽" },
  { name: "hot_pepper", emoji: "🌶️" }, { name: "cucumber", emoji: "🥒" },
  { name: "broccoli", emoji: "🥦" }, { name: "garlic", emoji: "🧄" },
  { name: "onion", emoji: "🧅" }, { name: "peanuts", emoji: "🥜" },
  { name: "bread", emoji: "🍞" }, { name: "croissant", emoji: "🥐" },
  { name: "baguette", emoji: "🥖" }, { name: "pretzel", emoji: "🥨" },
  { name: "bagel", emoji: "🥯" }, { name: "pancakes", emoji: "🥞" },
  { name: "waffle", emoji: "🧇" }, { name: "cheese", emoji: "🧀" },
  { name: "meat", emoji: "🍖" }, { name: "poultry_leg", emoji: "🍗" },
  { name: "bacon", emoji: "🥓" }, { name: "hamburger", emoji: "🍔" },
  { name: "burger", emoji: "🍔" }, { name: "fries", emoji: "🍟" },
  { name: "hotdog", emoji: "🌭" }, { name: "sandwich", emoji: "🥪" },
  { name: "taco", emoji: "🌮" }, { name: "burrito", emoji: "🌯" },
  { name: "falafel", emoji: "🧆" }, { name: "egg", emoji: "🥚" },
  { name: "fried_egg", emoji: "🍳" }, { name: "cooking", emoji: "🍳" },
  { name: "salad", emoji: "🥗" }, { name: "popcorn", emoji: "🍿" },
  { name: "salt", emoji: "🧂" }, { name: "stew", emoji: "🍲" },
  { name: "spaghetti", emoji: "🍝" }, { name: "pasta", emoji: "🍝" },
  { name: "ramen", emoji: "🍜" }, { name: "curry", emoji: "🍛" },
  { name: "sushi", emoji: "🍣" }, { name: "bento", emoji: "🍱" },
  { name: "dumpling", emoji: "🥟" }, { name: "rice", emoji: "🍚" },
  { name: "ice_cream", emoji: "🍨" }, { name: "icecream", emoji: "🍦" },
  { name: "shaved_ice", emoji: "🍧" }, { name: "doughnut", emoji: "🍩" },
  { name: "donut", emoji: "🍩" }, { name: "cookie", emoji: "🍪" },
  { name: "birthday", emoji: "🎂" }, { name: "cupcake", emoji: "🧁" },
  { name: "pie", emoji: "🥧" }, { name: "chocolate", emoji: "🍫" },
  { name: "candy", emoji: "🍬" }, { name: "lollipop", emoji: "🍭" },
  { name: "honey", emoji: "🍯" }, { name: "milk", emoji: "🥛" },
  { name: "tea", emoji: "🍵" }, { name: "bubble_tea", emoji: "🧋" },
  { name: "beers", emoji: "🍻" }, { name: "cheers", emoji: "🥂" },
  { name: "clinking_glasses", emoji: "🥂" }, { name: "wine", emoji: "🍷" },
  { name: "wine_glass", emoji: "🍷" }, { name: "cocktail", emoji: "🍸" },
  { name: "tropical_drink", emoji: "🍹" }, { name: "whisky", emoji: "🥃" },
  { name: "tumbler", emoji: "🥃" }, { name: "champagne", emoji: "🍾" },
  { name: "sake", emoji: "🍶" }, { name: "juice", emoji: "🧃" },
  { name: "ice", emoji: "🧊" }, { name: "fork_knife", emoji: "🍴" },
  // doen, feest, sport
  { name: "confetti", emoji: "🎊" }, { name: "balloon", emoji: "🎈" },
  { name: "gift", emoji: "🎁" }, { name: "present", emoji: "🎁" },
  { name: "ribbon", emoji: "🎀" }, { name: "christmas_tree", emoji: "🎄" },
  { name: "jack_o_lantern", emoji: "🎃" }, { name: "fireworks", emoji: "🎆" },
  { name: "sparkler", emoji: "🎇" }, { name: "firecracker", emoji: "🧨" },
  { name: "soccer", emoji: "⚽" }, { name: "football", emoji: "⚽" },
  { name: "basketball", emoji: "🏀" }, { name: "american_football", emoji: "🏈" },
  { name: "baseball", emoji: "⚾" }, { name: "tennis", emoji: "🎾" },
  { name: "volleyball", emoji: "🏐" }, { name: "rugby", emoji: "🏉" },
  { name: "ping_pong", emoji: "🏓" }, { name: "badminton", emoji: "🏸" },
  { name: "golf", emoji: "⛳" }, { name: "bowling", emoji: "🎳" },
  { name: "ski", emoji: "🎿" }, { name: "snowboarder", emoji: "🏂" },
  { name: "ice_skate", emoji: "⛸️" }, { name: "boxing", emoji: "🥊" },
  { name: "martial_arts", emoji: "🥋" }, { name: "dart", emoji: "🎯" },
  { name: "bullseye", emoji: "🎯" }, { name: "kite", emoji: "🪁" },
  { name: "fishing", emoji: "🎣" }, { name: "diving", emoji: "🤿" },
  { name: "canoe", emoji: "🛶" }, { name: "kayak", emoji: "🛶" },
  { name: "sailboat", emoji: "⛵" }, { name: "video_game", emoji: "🎮" },
  { name: "joystick", emoji: "🕹️" }, { name: "dice", emoji: "🎲" },
  { name: "game_die", emoji: "🎲" }, { name: "chess", emoji: "♟️" },
  { name: "puzzle", emoji: "🧩" }, { name: "art", emoji: "🎨" },
  { name: "palette", emoji: "🎨" }, { name: "movie", emoji: "🎬" },
  { name: "clapper", emoji: "🎬" }, { name: "camera", emoji: "📷" },
  { name: "video_camera", emoji: "📹" }, { name: "tv", emoji: "📺" },
  { name: "headphones", emoji: "🎧" }, { name: "notes", emoji: "🎶" },
  { name: "guitar", emoji: "🎸" }, { name: "piano", emoji: "🎹" },
  { name: "saxophone", emoji: "🎷" }, { name: "trumpet", emoji: "🎺" },
  { name: "violin", emoji: "🎻" }, { name: "drum", emoji: "🥁" },
  { name: "ticket", emoji: "🎟️" }, { name: "circus", emoji: "🎪" },
  { name: "performing_arts", emoji: "🎭" }, { name: "book", emoji: "📖" },
  { name: "books", emoji: "📚" }, { name: "newspaper", emoji: "📰" },
  // reizen en plekken
  { name: "car", emoji: "🚗" }, { name: "taxi", emoji: "🚕" },
  { name: "bus", emoji: "🚌" }, { name: "truck", emoji: "🚚" },
  { name: "van", emoji: "🚐" }, { name: "police_car", emoji: "🚓" },
  { name: "ambulance", emoji: "🚑" }, { name: "fire_engine", emoji: "🚒" },
  { name: "racing_car", emoji: "🏎️" }, { name: "motorcycle", emoji: "🏍️" },
  { name: "scooter", emoji: "🛵" }, { name: "bike", emoji: "🚲" },
  { name: "bicycle", emoji: "🚲" }, { name: "train", emoji: "🚆" },
  { name: "metro", emoji: "🚇" }, { name: "tram", emoji: "🚊" },
  { name: "airplane", emoji: "✈️" }, { name: "plane", emoji: "✈️" },
  { name: "helicopter", emoji: "🚁" }, { name: "boat", emoji: "🚤" },
  { name: "ship", emoji: "🚢" }, { name: "anchor", emoji: "⚓" },
  { name: "fuel", emoji: "⛽" }, { name: "construction", emoji: "🚧" },
  { name: "traffic_light", emoji: "🚦" }, { name: "map", emoji: "🗺️" },
  { name: "house", emoji: "🏠" }, { name: "home", emoji: "🏠" },
  { name: "office", emoji: "🏢" }, { name: "hospital", emoji: "🏥" },
  { name: "school", emoji: "🏫" }, { name: "hotel", emoji: "🏨" },
  { name: "castle", emoji: "🏰" }, { name: "stadium", emoji: "🏟️" },
  { name: "tent", emoji: "⛺" }, { name: "statue_of_liberty", emoji: "🗽" },
  { name: "eiffel_tower", emoji: "🗼" }, { name: "ferris_wheel", emoji: "🎡" },
  { name: "roller_coaster", emoji: "🎢" }, { name: "luggage", emoji: "🧳" },
  { name: "passport", emoji: "🛂" }, { name: "flag", emoji: "🏁" },
  { name: "checkered_flag", emoji: "🏁" }, { name: "rainbow_flag", emoji: "🏳️‍🌈" },
  { name: "pirate_flag", emoji: "🏴‍☠️" }, { name: "white_flag", emoji: "🏳️" },
  // dingen
  { name: "watch", emoji: "⌚" }, { name: "alarm_clock", emoji: "⏰" },
  { name: "hourglass", emoji: "⏳" }, { name: "stopwatch", emoji: "⏱️" },
  { name: "calendar", emoji: "📅" }, { name: "date", emoji: "📅" },
  { name: "pushpin", emoji: "📌" }, { name: "pin", emoji: "📍" },
  { name: "paperclip", emoji: "📎" }, { name: "scissors", emoji: "✂️" },
  { name: "pencil", emoji: "✏️" }, { name: "pen", emoji: "🖊️" },
  { name: "memo", emoji: "📝" }, { name: "clipboard", emoji: "📋" },
  { name: "folder", emoji: "📁" }, { name: "chart", emoji: "📈" },
  { name: "chart_down", emoji: "📉" }, { name: "bar_chart", emoji: "📊" },
  { name: "package", emoji: "📦" }, { name: "mailbox", emoji: "📬" },
  { name: "envelope", emoji: "✉️" }, { name: "bell", emoji: "🔔" },
  { name: "no_bell", emoji: "🔕" }, { name: "megaphone", emoji: "📣" },
  { name: "loudspeaker", emoji: "📢" }, { name: "speech_bubble", emoji: "💬" },
  { name: "thought_bubble", emoji: "💭" }, { name: "zzz", emoji: "💤" },
  { name: "battery", emoji: "🔋" }, { name: "plug", emoji: "🔌" },
  { name: "keyboard", emoji: "⌨️" }, { name: "desktop", emoji: "🖥️" },
  { name: "printer", emoji: "🖨️" }, { name: "cd", emoji: "💿" },
  { name: "floppy", emoji: "💾" }, { name: "satellite", emoji: "📡" },
  { name: "magnifying_glass", emoji: "🔍" }, { name: "mag", emoji: "🔍" },
  { name: "flashlight", emoji: "🔦" }, { name: "candle", emoji: "🕯️" },
  { name: "money", emoji: "💵" }, { name: "dollar", emoji: "💵" },
  { name: "euro", emoji: "💶" }, { name: "credit_card", emoji: "💳" },
  { name: "gem", emoji: "💎" }, { name: "diamond", emoji: "💎" },
  { name: "ring", emoji: "💍" }, { name: "crown", emoji: "👑" },
  { name: "tophat", emoji: "🎩" }, { name: "cap", emoji: "🧢" },
  { name: "glasses", emoji: "👓" }, { name: "dark_sunglasses", emoji: "🕶️" },
  { name: "tshirt", emoji: "👕" }, { name: "jeans", emoji: "👖" },
  { name: "dress", emoji: "👗" }, { name: "bikini", emoji: "👙" },
  { name: "shoe", emoji: "👟" }, { name: "sneaker", emoji: "👟" },
  { name: "high_heel", emoji: "👠" }, { name: "boot", emoji: "🥾" },
  { name: "handbag", emoji: "👜" }, { name: "backpack", emoji: "🎒" },
  { name: "umbrella2", emoji: "☂️" }, { name: "lipstick", emoji: "💄" },
  { name: "hammer", emoji: "🔨" }, { name: "wrench", emoji: "🔧" },
  { name: "tools", emoji: "🛠️" }, { name: "gear", emoji: "⚙️" },
  { name: "link", emoji: "🔗" }, { name: "chains", emoji: "⛓️" },
  { name: "magnet", emoji: "🧲" }, { name: "pill", emoji: "💊" },
  { name: "syringe", emoji: "💉" }, { name: "thermometer", emoji: "🌡️" },
  { name: "broom", emoji: "🧹" }, { name: "soap", emoji: "🧼" },
  { name: "toilet_paper", emoji: "🧻" }, { name: "bathtub", emoji: "🛁" },
  { name: "bed", emoji: "🛏️" }, { name: "couch", emoji: "🛋️" },
  { name: "door", emoji: "🚪" }, { name: "teddy_bear", emoji: "🧸" },
  { name: "bomb", emoji: "💣" }, { name: "knife", emoji: "🔪" },
  { name: "shield", emoji: "🛡️" }, { name: "crystal_ball", emoji: "🔮" },
  { name: "nazar", emoji: "🧿" }, { name: "magic_wand", emoji: "🪄" },
  { name: "unlock", emoji: "🔓" }, { name: "moyai", emoji: "🗿" },
  // tekens
  { name: "heavy_check", emoji: "✔️" }, { name: "question", emoji: "❓" },
  { name: "exclamation", emoji: "❗" }, { name: "bangbang", emoji: "‼️" },
  { name: "interrobang", emoji: "⁉️" }, { name: "no_entry", emoji: "⛔" },
  { name: "stop", emoji: "🛑" }, { name: "prohibited", emoji: "🚫" },
  { name: "recycle", emoji: "♻️" }, { name: "infinity", emoji: "♾️" },
  { name: "plus", emoji: "➕" }, { name: "minus", emoji: "➖" },
  { name: "arrow_up", emoji: "⬆️" }, { name: "arrow_down", emoji: "⬇️" },
  { name: "arrow_left", emoji: "⬅️" }, { name: "arrow_right", emoji: "➡️" },
  { name: "repeat", emoji: "🔁" }, { name: "new", emoji: "🆕" },
  { name: "free", emoji: "🆓" }, { name: "sos", emoji: "🆘" },
  { name: "up", emoji: "🆙" }, { name: "cool_button", emoji: "🆒" },
  { name: "red_circle", emoji: "🔴" }, { name: "green_circle", emoji: "🟢" },
  { name: "blue_circle", emoji: "🔵" }, { name: "yellow_circle", emoji: "🟡" },
  { name: "black_circle", emoji: "⚫" }, { name: "white_circle", emoji: "⚪" },
  { name: "peace_symbol", emoji: "☮️" }, { name: "yin_yang", emoji: "☯️" },
  { name: "anger", emoji: "💢" }, { name: "boom", emoji: "💥" },
  { name: "collision", emoji: "💥" }, { name: "sweat_drops", emoji: "💦" },
  { name: "dash", emoji: "💨" }, { name: "hole", emoji: "🕳️" },
  { name: "copyright", emoji: "©️" }, { name: "tm", emoji: "™️" },
  { name: "wave_hand", emoji: "👋" }, { name: "thumbs_up", emoji: "👍" },
  { name: "thumbs_down", emoji: "👎" },
];

/**
 * `:)` wordt 🙂 terwijl je typt.
 *
 * Een emoticon die op een letter eindigt (`:S`, `:P`, `:O`, `:X`, `:D`,
 * `B)` niet, maar `:S` wel) wacht tot er een spatie of leesteken achter
 * staat. Hij verving eerst ook aan het eind van de tekst — en dat is
 * precies waar je staat als je `:sun` begint te typen: bij `:s` stond er
 * al 😖, en `:pizza`, `:ocean` en `:x` liepen net zo vast. Een emoticon
 * van tekens (`:)`, `<3`) mag wel meteen: geen naam begint met `)`.
 */
export function replaceEmoticons(text: string): string {
  let result = text;
  for (const [pattern, emoji] of EMOTICON_MAP) {
    result = result.replace(pattern, (match, offset, str) => {
      const after = str[offset + match.length];
      if (after === undefined) return /[a-z]$/i.test(match) ? match : emoji;
      if (/[\s.,!?]/.test(after)) return emoji;
      return match;
    });
  }
  return result;
}

/**
 * Wat bij `:q` past, het beste eerst.
 *
 * Eerst de naam die precies `q` is (`:bee` → 🐝, niet 🍺), dan namen die
 * mét `q` beginnen (`:mon` → monkey, niet lemon), dan
 * namen waarin een deel met `q` begint (`:hea` → broken_heart), dan de
 * rest waarin hij ergens staat. Eén emoji telt één keer: heart en
 * red_heart zijn allebei ❤️, en anders kostte hij twee van de acht plekken.
 */
export function emojiSuggestionsFor(query: string): { name: string; emoji: string }[] {
  if (query.length < 2) return [];
  const q = query.toLowerCase();
  const rank = (name: string) =>
    name === q
      ? 0
      : name.startsWith(q)
        ? 1
        : name.split("_").some((part) => part.startsWith(q))
          ? 2
          : name.includes(q)
            ? 3
            : -1;
  const hits = EMOJI_SHORTCODES.map((e, i) => ({ ...e, r: rank(e.name), i }))
    .filter((e) => e.r >= 0)
    .sort((a, b) => a.r - b.r || a.i - b.i);
  const seen = new Set<string>();
  const out: { name: string; emoji: string }[] = [];
  for (const { name, emoji } of hits) {
    if (seen.has(emoji)) continue;
    seen.add(emoji);
    out.push({ name, emoji });
    if (out.length === 8) break;
  }
  return out;
}
